version: "3.7"
services:
  api:
    build:
      context: ./api
    command: gunicorn --bind 0.0.0.0:5000 --workers 3 wsgi:app 
    restart: always
    ports:
     - 5000:5000
    environment:
      - FLASK_DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - ROLLBAR_KEY=blah
      - ROLLBAR_APP=projname
    depends_on:
      - redis

  worker:
    user: nobody
    build:
      context: ./worker
    command: celery -A tasks worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - ROLLBAR_KEY=blah
      - ROLLBAR_APP=projname
    depends_on:
      - redis

  monitor:
    build:
      context: ./monitor
    ports:
     - 5555:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    entrypoint: flower
    command:  --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis
